eng/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tracker.urls', 'tracker')),
    path('',include('accounts.urls')),
]

tracker/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'tracker'

urlpatterns = [
        path('',views.home, name= 'home'),
        path('new-client',views.new_client, name='new_client'),
        path('new-proposal',views.new_proposal, name='new_proposal'),
        path('dashboard', views.dashboard, name='dashboard'),
        path('dasher/', views.dasher, name='dasher'),
        path('invoices/', views.all_invoices, name = 'all_invoices'),
        path('search',views.search, name='search'),
        path('dashboard/add_target/', views.add_target, name='add_target'),
        path('<int:pk>/detail/', views.detail, name='detail'),
        path('<int:pk>/detail/client-edit', views.ClientEdit.as_view(), name='client_edit'),
        path('<int:pk>/detail/notes/', views.detail, name='notes'),
        path('<int:pk>/create-engagement/', views.create_engagement, name='create_engagement'),
        path('<int:pk>/detail/<int:engagement_pk>/', views.edit_engagement, name='edit_engagement'),
        path('<int:pk>/detail/<int:engagement_pk>/invoices/', views.EngagementInvoice.as_view(), name='engagement_invoices'),
        path('<int:pk>/detail/<int:engagement_pk>/eng_details/', views.EngagementPayment.as_view(), name='eng_details'),
        path('<int:pk>/detail/<int:engagement_pk>/create-invoice/', views.create_invoice, name='create_invoice'),
        path('<int:pk>/detail/<int:engagement_pk>/payment/', views.create_payment, name='create_payment'),
        re_path(r'^(?P<client_id>[0-9]+)/delete-engagement/^(?P<engagement_id>[0-9]+)/$', views.delete_engagement, name='delete_engagement'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/add_target.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
  <form method="post" id ="id-target-form" enctype="multipart/form-data">
    {% csrf_token %}
    {% crispy form %}
  </form>
</div>

{% endblock %}

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Engagement Tracker{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
</head>
<body>
  <nav class="navbar navbar-inverse">
      <div class="container-fluid">

          <!-- Header -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'tracker:home' %}">MAZARS BRJ</a>
          </div>

          <!-- Items -->
          <div class="collapse navbar-collapse" id="topNavBar">
              <ul class="nav navbar-nav">
                  <li class="#"><a href="{% url 'tracker:home' %}"><span class="glyphicon glyphicon-user"></span>&nbsp; Clients</a></li>
                  <li class="#"><a href="{% url 'tracker:new_proposal' %}"><span class="glyphicon glyphicon-plus"></span>&nbsp; Proposals</a></li>
                  <li class="#"><a href="{% url 'tracker:search' %}"><span class="glyphicon glyphicon-link" aria-hidden="true"></span>&nbsp; Engagements</a></li>
                  <li class="#"><a href="{% url 'tracker:all_invoices' %}"><span class="glyphicon glyphicon-flag" aria-hidden="true"></span>&nbsp; Invoices</a></li>
                  <li class="#"><a href="#"><span class="glyphicon glyphicon-bell"></span>&nbsp; Notifications <span class="badge badge-light">0</span></a></li>
              </ul>

              <ul class="nav navbar-nav navbar-right">

                <li>
                   <form id="demo-2">
                        {{ filter.as_p }}
                      <input type="search" placeholder="Search">
                    </form>
                </li>

                  <li>
                      <a href="{% url 'tracker:dashboard' %}">
                          <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>&nbsp; DASH BOARD
                      </a>
                  </li>
                {% if user.is_authenticated %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      {{ user.username|title }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                      <a class="dropdown-item" href="{% url 'password_reset' %}">Change password</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                    </div>
                  </li>

            {% else %}
            <li>
            <form class="form-inline ml-auto">
              <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a></li>
              <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a></li>
            </form>
            </li>
      {% endif %}
        </ul>
          </div>

      </div>
  </nav>

  {% include 'includes/messages.html' %}
  {% block content %}
  {% endblock %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/search.ajax' %}"></script>
<script src="{% static 'js/totals.js' %}"></script>
<script src="{% static 'js/export.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block javascript %}
{% endblock %}
</body>
</html>

templates/client_dash.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    
  </body>
</html>

templates/create_proposal.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="alert alert-danger" role="alert" align=center>
    <h3>NO PROPOSAL</h3>
  </div>
</div>

{% endblock %}

templates/dasher.html
{% include 'base.html' %}

{% block content %}

{% load mathfilters %}
{% load humanize %}


{% load staticfiles %}

<script src="{% static 'js/behaviour.js' %}"></script>

<div class="container">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link primary" href="#">All</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Audit</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Tax</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">TaxCom</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">AOS</a>
      </li>
    </ul>
</div>

    <br>

<div class="container">
  <div class="col-sm-6">
    <h1>New All</h1>
    {% for client in new %}

    <ul>
    <li>{{ client.client.currency }}-{{ client.active }}</li>
    </ul>

  {% endfor %}
  </div>
  <div class="col-sm-6">
    <h1>Existing All
      <small>(In progress work)</small>

    </h1>
    {% for clientie in existing %}

    <ul>
    <li>{{ clientie.client }}-{{ clientie.active }}</li>
    </ul>
  {% endfor %}
  </div>
</div>

<div class="container">
  <div class="col-sm-6">
    <h1>Invoices/ Billed</h1>
    {% for clientie in invoiced %}
    {% for pay in payment %}

    <ul>
    <li>{{ clientie.engagement.client }}-{{ clientie.amount}}</li>
    <li>{{ pay.amount}}</li>
    <li>{{clientie.amount|sub:pay.amount}}</li>

    <li>
      <div class="progress">
        <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">Engaged(25%)</div>
      </div>
    </li>

    </ul>
  {% endfor %}
  {% endfor %}
  </div>

  <div class="col-sm-6">
      <h1>Lost Clients</h1>
  </div>
</div>


<div class="container">
  <div class="card">
    <div class="card-body">
      <table class="table table-sm">
        <thead>
          <tr>
            <th scope="col">Client</th>
            <th scope="col">Assignment</th>
            <th scope="col">Amount</th>
            <th scope="col">Work Progress</th>
            <th scope="col">Invoiced</th>
            <th scope="col">Paid</th>
            <th scope="col">Balance</th>
          </tr>
        </thead>

        {% for client_new in new%}
        {% for invoice in invoiced %}
        {% for pay in payment %}
        <tbody>
          <tr>
            <th scope="row">{{client_new.client.name|intcomma|truncatechars:12|upper}}</th>
            <th scope="row">{{client_new.assignment|intcomma|truncatechars:10}}</th>
            <th scope="row">{{client_new.active|intcomma }}</th>
            <th scope="row">
              <div class="progress">
                <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 100%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">Engaged(100%)</div>
              </div>
            </th>
            <th scope="row">{{invoice.amount|intcomma }}</th>
            <th scope="row">{{pay.amount|intcomma }}</th>
            <th scope="row">{{client_new.active|sub:pay.amount|intcomma }}</th>
          </tr>
        </tbody>
        {% endfor %}
        {% endfor %}
        {% endfor %}
      </table>
    </div>

    </div>
  </div>




  <table>
  <tr>
    <td>
      <input value="1" />
    </td>
    <td>
      <input value="2" />
    </td>
    <td>
      <input value="3" />
    </td>
    <td class="rowsum">-</td>
  </tr>
  <tr>
    <td>
      <input value="4" />
    </td>
    <td>
      <input value="5" />
    </td>
    <td>
      <input value="6" />
    </td>
    <td class="rowsum">-</td>
  </tr>
  <tr>
    <td>
      <input value="7" />
    </td>
    <td>
      <input value="8" />
    </td>
    <td>
      <input value="9" />
    </td>
    <td class="rowsum">-</td>
  </tr>
  <tr>
    <td class="colsum">-</td>
    <td class="colsum">-</td>
    <td class="colsum">-</td>
  </tr>
</table>


{% endblock %}

templates/eng_details.html
{% extends 'base.html' %}
{% load mathfilters %}

{% block content %}
{% load humanize %}

{% if invoices %}
{% for invoice in invoices %}

<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Assignment</th>
        <th scope="col">Reference</th>
        <th scope="col" colspan="2" align='right'>Payment <button type="button" class="btn btn-primary"> PAY</button></th>
        <th scope="col">Balance</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td></td>
        <td>{{invoice.reference}}<br> <small>{{invoice.amount|intcomma}}</small>
        </td>
        <td>Percent</td>
        <td>Amount</td>
        <td></td>
      </tr>

      {% if payments %}
      {% for payment in payments %}
      <tr>
        <td colspan="2"></td>
        <td>50%</td>
        <td>{{payment.amount}}</td>
        <td>@fat</td>
      </tr>
      {% endfor %}
      {% else %}
      <tr>
        <td span="2"></td>
        <td colspan="4" align="middle">Not paid yet</td>
      {% endif %}
      </tr>
    </tbody>
  </table>
  {% endfor %}

  {% else %}
  <div class="alert alert-danger" role="alert" align=center>
    <h3>Not Invoiced Yet <a href="{% url 'tracker:create_invoice' engagement.client.pk engagement.pk %}">Add Invoice</a></h3>
  </div>
</div>

{% endif %}

{% endblock %}

templates/engagement_create.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}

{% load static %}

<script scr="{% static 'js/notes.js' %}"></script>

<div class="container">
  <h1>Add Engagement</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% crispy form %}
  </form>
</div>
{% endblock %}

templates/engagement_details.html
{% extends 'base.html' %}
{% load mathfilters %}

{% block content %}
{% load humanize %}

{% if invoices %}
{% for invoice in invoices %}

<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Assignment</th>
        <th scope="col">Reference</th>
        <th scope="col"> Bill</th>
        <th scope="col">Percent</th>
        <th scope="col">Amount</th>
        <th scope="col">Balance</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td></td>
        <td>{{invoice.reference}}</td>
        <td>${{invoice.amount|intcomma}}</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>

      {% if payments %}
      {% for payment in payments %}
      <tr>
        <td colspan="2"></td>
        <td>50%</td>
        <td>{{payment.amount}}</td>
        <td>@fat</td>
      </tr>
      {% endfor %}
      {% else %}
      <tr>
        <td span="2"></td>
        <td colspan="4" align="middle">Not paid yet</td>
      {% endif %}
      </tr>
    </tbody>
  </table>
  {% endfor %}

  {% else %}
  <div class="alert alert-danger" role="alert" align=center>
    <h3>Not Invoiced Yet <a href="{% url 'tracker:create_invoice' engagement.client.pk engagement.pk %}">Add Invoice</a></h3>
  </div>
</div>

{% endif %}

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load staticfiles %}

{% block content %}
<div class="container">

<ul>
<button type="button" class="btn btn-secondary">
  CLIENTS <span class="badge badge-light">{{count}}</span>
</button>
<a href="{% url 'tracker:new_client' %}" class="btn btn-primary">Add Client</a>
</ul>

<hr size="30">
{% if clients %}

<div class="container">
  <div class="row">
    {% for client in clients %}
     <div class="col-xs-5 col-md-3">
           <a href="{% url 'tracker:detail' client.pk %}">
           {% if client.company_logo %}
           <img src="{{ client.logo.url }}">
           {% else %}
           <img src="{% static 'image/mazarslogo.jpg' %}">
           {% endif %}
           <center><h5 class="card-title" style ="padding-bottom: 25px;" >{{ client.name|truncatechars:30|upper }}</h5></center>
           </a>
     </div>
     {% endfor %}
  </div>
</div>

{% else %}
<div class="alert alert-danger" role="alert" align=center>
  <h3>No Client Added Yet</h3>
</div>
{% endif %}

{% endblock %}

templates/invoice_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <center>  <h3>ADD INVOICE</h3> </center>
  <form method="post" id='invoice-create-form' enctype="multipart/form-data">
    {% csrf_token %}
    {% crispy form %}
  </form>
</div>
{% endblock %}

templates/invoices.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th scope="col">Reference</th>
        <th scope="col">Date</th>
        <th scope="col">Amount</th>
      </tr>
    </thead>
    <tbody>

    {% for invoice in all_inv %}
      <tr>
        <td>{{invoice.invoices__client}}</td>
        <td>{{invoice.date}}</td>
        <td>{{invoice.amount}}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock%}

templates/notifications.html
{% include 'base.html' %}

{% block content %}

<div class="container">
  <form method='GET' action='{% url "tracker:notify" %}' class="form my-2 my-lg-0">
  <div class='input-group'>
    <input class="form-control" type="text" placeholder="Search" name='q' aria-label="Search" value='{{ request.GET.q }}'>
    <span class='input-group-btn'>
        <button class="btn btn-outline-success" type="submit">Search</button>
    </span>
    </div>
</form>
</div>

{% endblock %}

templates/payment.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Next →</button>
  </form>
</div>

{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% load humanize %}

{% load widget_tweaks %}
{% load static %}

{% block content %}
<div class="container">
  <form method="get">
    <div class="well">
      <h4 style="margin-top: 0">Engagement Search</h4>
      <div class="row">
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.year.label_tag }}
          {% render_field filter.form.year class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.assignment.label_tag }}
          {% render_field filter.form.assignment class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.currency.label_tag }}
          {% render_field filter.form.currency class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.type.label_tag }}
          {% render_field filter.form.type class="form-control" %}
        </div>
        <div class="form-group col-sm-8 col-md-6">
          {{ filter.form.client.label_tag }}
          {% render_field filter.form.client class="form-control" %}
        </div>
      </div>
      <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Search
      </button>
      <button class="btn btn-success" id="btnExport" onclick="javascript:xport.toCSV('testTable');"> Export to CSV</button> <em>&nbsp;&nbsp;&nbsp;</em>
      </button>
    </div>
  </form>

<!-- <script src="{% static 'js/behaviour.js' %}"></script> -->

  <table class="table table-sm table-striped table-hover" id="testTable">
    <thead>
      <tr>
        <th scope="col">Service</th>
        <th scope="col">Client</th>
        <th scope="col">Reference</th>
        <th scope="col">Engagement Ending</th>
        <th scope="col">Rate</th>
        <th scope="col">Factor</th>
        <th scope="col">Active</th>
        <th scope="col">Currency</th>
      </tr>
    </thead>
    <tbody>
      {% for engagement in filter.qs %}
        <tr>
          <td>{{engagement.assignment}}</a></td>
          <td>{{engagement.client|truncatechars:30}}</td>
          <td>{{engagement.reference}}</td>
          <td>{{engagement.engagement_ending}}</td>
          <td align="right">{{engagement.rate}}</td>
          <td align="right">{{engagement.factor}}</td>
          <td align="right">{{engagement.active}}</td>
          <td>{{engagement.currency}}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="8" align="middle" class="alert alert-danger" role="alert">NO DATA FOUND FOR THE SEARCH</td>
        </tr>
      {% endfor %}
      <tfoot>
        <tr>
          <td align="right">TOTAL</td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
        </tr>
      </tfoot>
    </tbody>
  </table>
</div>

{% endblock %}